package admin

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/zero-color/ecforce-go"
)

// Customer is a shop customer (顧客). It is the union of the attributes of the
// normal and lighter response variants; fields absent from the variant in use
// are left at their zero value.
type Customer struct {
	ID                    int64         `json:"id"`
	AuthenticationToken   string        `json:"authentication_token"`
	Number                string        `json:"number"`
	State                 string        `json:"state"`
	HumanStateName        string        `json:"human_state_name"`
	CustomerRankID        int64         `json:"customer_rank_id"`
	CustomerRankName      string        `json:"customer_rank_name"`
	Email                 string        `json:"email"`
	MobileEmail           string        `json:"mobile_email"`
	SexID                 int64         `json:"sex_id"`
	Sex                   string        `json:"sex"`
	JobID                 int64         `json:"job_id"`
	Job                   string        `json:"job"`
	Birth                 *ecforce.Time `json:"birth"`
	BuyTimes              int           `json:"buy_times"`
	BuyTotal              int           `json:"buy_total"`
	FirstOrderCompletedAt *ecforce.Time `json:"first_order_completed_at"`
	LastOrderCompletedAt  *ecforce.Time `json:"last_order_completed_at"`
	Point                 int           `json:"point"`
	PointExpiredAt        *ecforce.Time `json:"point_expired_at"`
	CustomerTypeID        int64         `json:"customer_type_id"`
	CustomerTypeName      string        `json:"customer_type_name"`
	Optin                 bool          `json:"optin"`
	LineID                string        `json:"line_id"`
	LineIDLinkedAt        *ecforce.Time `json:"line_id_linked_at"`
	TenantID              int64         `json:"tenant_id"`
	AssignedAdminID       int64         `json:"assigned_admin_id"`
	LinkedMemo            string        `json:"linked_memo"`
	MailDeliveryStop      bool          `json:"mail_delivery_stop"`
	NPRoyalCustomer       bool          `json:"np_royal_customer"`
	Blacklist             bool          `json:"blacklist"`
	BlacklistReasons      string        `json:"blacklist_reasons"`
	Labels                string        `json:"labels"`
	CouponCodes           string        `json:"coupon_codes"`
	LinkNumber            string        `json:"link_number"`
	IsAutoGeneratedEmail  bool          `json:"is_auto_generated_email"`
	AuthInfrastructureID  string        `json:"auth_infrastructure_id"`
	Option01              string        `json:"option01"`
	Option02              string        `json:"option02"`
	Option03              string        `json:"option03"`
	Option04              string        `json:"option04"`
	Option05              string        `json:"option05"`
	Option06              string        `json:"option06"`
	Option07              string        `json:"option07"`
	Option08              string        `json:"option08"`
	Option09              string        `json:"option09"`
	Option10              string        `json:"option10"`
	CreatedAt             *ecforce.Time `json:"created_at"`
	UpdatedAt             *ecforce.Time `json:"updated_at"`
	DeletedAt             *ecforce.Time `json:"deleted_at"`
}

// Note is a customer memo (メモ) side-loaded via include.
type Note struct {
	ID         int64         `json:"id"`
	Content    string        `json:"content"`
	CreatedAt  *ecforce.Time `json:"created_at"`
	UpdatedAt  *ecforce.Time `json:"updated_at"`
	OperatedAt *ecforce.Time `json:"operated_at"`
}

// Point is a customer point ledger entry (ポイント).
type Point struct {
	ID                         int64         `json:"id"`
	CustomerID                 int64         `json:"customer_id"`
	PointEventID               int64         `json:"point_event_id"`
	PointEventType             string        `json:"point_event_type"`
	PointEventName             string        `json:"point_event_name"`
	PointEventDescription      string        `json:"point_event_description"`
	Point                      int           `json:"point"`
	PointTotal                 int           `json:"point_total"`
	FirstExpiredPointTotal     int           `json:"first_expired_point_total"`
	FirstExpiredPointExpiredAt *ecforce.Time `json:"first_expired_point_expired_at"`
	FirstLimitedPointTotal     int           `json:"first_limited_point_total"`
	FirstLimitedPointExpiredAt *ecforce.Time `json:"first_limited_point_expired_at"`
	CreatedAt                  *ecforce.Time `json:"created_at"`
	UpdatedAt                  *ecforce.Time `json:"updated_at"`
	DeletedAt                  *ecforce.Time `json:"deleted_at"`
}

// CreditCard is a stored credit card (クレジットカード) side-loaded via include.
type CreditCard struct {
	ID                       int64  `json:"id"`
	Month                    int    `json:"month"`
	Year                     int    `json:"year"`
	LastDigits               string `json:"last_digits"`
	Name                     string `json:"name"`
	GatewayCustomerProfileID string `json:"gateway_customer_profile_id"`
	GatewayPaymentProfileID  string `json:"gateway_payment_profile_id"`
	GatewayCardSeq           string `json:"gateway_card_seq"`
	AccessToken              string `json:"access_token"`
	ClientIP                 string `json:"client_ip"`
	Default                  bool   `json:"default"`
}

// MemberGroup is a member group (会員グループ) side-loaded via include.
type MemberGroup struct {
	ID     int64  `json:"id"`
	Name   string `json:"name"`
	Status bool   `json:"status"`
}

// CustomerPermittedVariant restricts a variant's sale to a customer
// (顧客限定商品).
type CustomerPermittedVariant struct {
	ID        int64         `json:"id"`
	VariantID int64         `json:"variant_id"`
	StartedAt *ecforce.Time `json:"started_at"`
	EndedAt   *ecforce.Time `json:"ended_at"`
}

// BlacklistReason is a blacklist reason master record (ブラックリスト理由).
type BlacklistReason struct {
	ID        int64         `json:"id"`
	Name      string        `json:"name"`
	Reason    string        `json:"reason"`
	CreatedAt *ecforce.Time `json:"created_at"`
	UpdatedAt *ecforce.Time `json:"updated_at"`
}

// OneDColorAnswer is a 1dcolor personalize survey answer side-loaded via
// include. AnswerResults keeps the raw survey answers (question ID, question,
// choice ID, choice, selection state, input) as the API does not document
// their structure.
type OneDColorAnswer struct {
	AnswerID           int64           `json:"answer_id"`
	PersonalizeID      int64           `json:"personalize_id"`
	Code               string          `json:"code"`
	Name               string          `json:"name"`
	Method             string          `json:"method"`
	Identifier         string          `json:"identifier"`
	AnswerStartedAt    *ecforce.Time   `json:"answer_started_at"`
	AccessDevice       string          `json:"access_device"`
	AccessOS           string          `json:"access_os"`
	AccessReferrer     int             `json:"access_referrer"`
	AnswerCompletedAt  *ecforce.Time   `json:"answer_completed_at"`
	CompleteActionID   int64           `json:"complete_action_id"`
	CompleteActionName string          `json:"complete_action_name"`
	CompleteAction     string          `json:"complete_action"`
	AnswerResults      json.RawMessage `json:"answer_results"`
}

// OneDColorAnswerScore is a score of a 1dcolor personalize survey answer
// side-loaded via include.
type OneDColorAnswerScore struct {
	AnswerID int64  `json:"answer_id"`
	Kind     string `json:"kind"`
	Score    int    `json:"score"`
}

// CustomerParams sets customer attributes on create/update requests. It is
// shared by Create, Update, BulkCreate and BulkUpdate; consult the API docs
// for which fields each endpoint accepts. ID identifies the target customer
// on bulk updates only.
type CustomerParams struct {
	ID               *int64           `json:"id,omitempty"`
	Email            *string          `json:"email,omitempty"`
	State            *string          `json:"state,omitempty"`
	CustomerRankID   *int64           `json:"customer_rank_id,omitempty"`
	CustomerTypeID   *int64           `json:"customer_type_id,omitempty"`
	Password         *string          `json:"password,omitempty"`
	SexID            *int64           `json:"sex_id,omitempty"`
	JobID            *int64           `json:"job_id,omitempty"`
	LineID           *string          `json:"line_id,omitempty"`
	TenantID         *int64           `json:"tenant_id,omitempty"`
	Birth            *ecforce.Date    `json:"birth,omitempty"`
	Optin            *ecforce.BoolInt `json:"optin,omitempty"`
	LinkNumber       *string          `json:"link_number,omitempty"`
	AssignedAdminID  *int64           `json:"assigned_admin_id,omitempty"`
	LinkedMemo       *string          `json:"linked_memo,omitempty"`
	MailDeliveryStop *ecforce.BoolInt `json:"mail_delivery_stop,omitempty"`
	IsBlacklist      *ecforce.BoolInt `json:"is_blacklist,omitempty"`
	// BlacklistReasonIDs requires IsBlacklist set to true in the same request.
	BlacklistReasonIDs []int64 `json:"blacklist_reason_ids,omitempty"`
	Option01           *string `json:"option01,omitempty"`
	Option02           *string `json:"option02,omitempty"`
	Option03           *string `json:"option03,omitempty"`
	Option04           *string `json:"option04,omitempty"`
	Option05           *string `json:"option05,omitempty"`
	Option06           *string `json:"option06,omitempty"`
	Option07           *string `json:"option07,omitempty"`
	Option08           *string `json:"option08,omitempty"`
	Option09           *string `json:"option09,omitempty"`
	Option10           *string `json:"option10,omitempty"`

	BillingAddressAttributes *AddressParams `json:"billing_address_attributes,omitempty"`
	// ShippingAddressAttributes sets the single shipping address of Create /
	// BulkCreate requests.
	ShippingAddressAttributes *AddressParams `json:"shipping_address_attributes,omitempty"`
	// ShippingAddressesAttributes sets multiple shipping addresses; entries
	// with an ID update that address, entries without one add a new address.
	ShippingAddressesAttributes []*AddressParams `json:"shipping_addresses_attributes,omitempty"`
	// PointAttributes grants points on Create / BulkCreate requests; only
	// PointEventID and Point apply.
	PointAttributes                            *PointParams                      `json:"point_attributes,omitempty"`
	NotesAttributes                            []*NoteParams                     `json:"notes_attributes,omitempty"`
	CustomerPermittedVariantsAttributes        []*CustomerPermittedVariantParams `json:"customer_permitted_variants_attributes,omitempty"`
	NeedToSendRegistrationCompleteNotification *ecforce.BoolInt                  `json:"need_to_send_registration_complete_notification,omitempty"`
}

// NoteParams sets a customer memo on update requests. An entry with an ID
// updates (or, with Delete, removes) that memo; an entry without one adds a
// new memo.
type NoteParams struct {
	ID         *int64           `json:"id,omitempty"`
	Content    *string          `json:"content,omitempty"`
	OperatedAt *ecforce.Time    `json:"operated_at,omitempty"`
	OperatedBy *int64           `json:"operated_by,omitempty"`
	Delete     *ecforce.BoolInt `json:"delete,omitempty"`
}

// CustomerPermittedVariantParams sets a customer-limited variant on update
// requests. An entry with an ID updates (or, with Delete, removes) that
// setting; an entry without one adds a new setting.
type CustomerPermittedVariantParams struct {
	ID        *int64           `json:"id,omitempty"`
	VariantID *int64           `json:"variant_id,omitempty"`
	StartedAt *ecforce.Time    `json:"started_at,omitempty"`
	EndedAt   *ecforce.Time    `json:"ended_at,omitempty"`
	Delete    *ecforce.BoolInt `json:"delete,omitempty"`
}

// PointParams creates a point ledger entry. For CreatePoint, set PointEventID
// (WithCreate false) or Name/Description (WithCreate true), Point as an
// absolute value, and AdditionAndSubtraction (false: subtract, true: add).
// As CustomerParams.PointAttributes, only PointEventID and Point apply.
type PointParams struct {
	PointEventID           *int64           `json:"point_event_id,omitempty"`
	Name                   *string          `json:"name,omitempty"`
	Description            *string          `json:"description,omitempty"`
	Point                  *int             `json:"point,omitempty"`
	AdditionAndSubtraction *ecforce.BoolInt `json:"addition_and_subtraction,omitempty"`
	WithCreate             *ecforce.BoolInt `json:"with_create,omitempty"`
}

// CustomerPointParams is one entry of a BulkCreatePoints request.
type CustomerPointParams struct {
	CustomerID             *int64           `json:"customer_id,omitempty"`
	PointEventID           *int64           `json:"point_event_id,omitempty"`
	Point                  *int             `json:"point,omitempty"`
	AdditionAndSubtraction *ecforce.BoolInt `json:"addition_and_subtraction,omitempty"`
}

// CreditCardParams sets credit card attributes on bulk create/update
// requests. ID identifies the target card on bulk updates only.
type CreditCardParams struct {
	ID                       *int64           `json:"id,omitempty"`
	Month                    *int             `json:"month,omitempty"`
	Year                     *int             `json:"year,omitempty"`
	LastDigits               *string          `json:"last_digits,omitempty"`
	Name                     *string          `json:"name,omitempty"`
	GatewayCustomerProfileID *string          `json:"gateway_customer_profile_id,omitempty"`
	GatewayPaymentProfileID  *string          `json:"gateway_payment_profile_id,omitempty"`
	GatewayCardSeq           *string          `json:"gateway_card_seq,omitempty"`
	AccessToken              *string          `json:"access_token,omitempty"`
	ClientIP                 *string          `json:"client_ip,omitempty"`
	Default                  *ecforce.BoolInt `json:"default,omitempty"`
}

// CustomerCreateRequest is the body of a Create request.
type CustomerCreateRequest struct {
	Customer                  *CustomerParams  `json:"customer"`
	CheckDuplicateLinkNumbers *ecforce.BoolInt `json:"check_duplicate_link_numbers,omitempty"`
}

// CustomerUpdateRequest is the body of an Update request.
type CustomerUpdateRequest struct {
	Customer *CustomerParams `json:"customer"`
	// UpdateMemberGroups re-links member groups: with MemberGroupIDs set, the
	// given groups are linked; without, currently matching groups are linked.
	UpdateMemberGroups *ecforce.BoolInt `json:"update_member_groups,omitempty"`
	MemberGroupIDs     []int64          `json:"member_group_ids,omitempty"`
}

// CustomerBulkRequest is the body of a BulkCreate or BulkUpdate request.
type CustomerBulkRequest struct {
	Customers                 []*CustomerParams `json:"customers"`
	CheckDuplicateLinkNumbers *ecforce.BoolInt  `json:"check_duplicate_link_numbers,omitempty"`
}

// CreditCardBulkRequest is the body of a BulkCreateCreditCards or
// BulkUpdateCreditCards request.
type CreditCardBulkRequest struct {
	CreditCards []*CreditCardParams `json:"credit_cards"`
	// RequestPaymentService forwards the change to the payment service.
	RequestPaymentService *ecforce.BoolInt `json:"request_payment_service,omitempty"`
}

// CreditCardBulkDestroyRequest is the body of a BulkDestroyCreditCards
// request.
type CreditCardBulkDestroyRequest struct {
	CreditCardIDs []int64 `json:"credit_card_ids"`
	// RequestPaymentService forwards the deletion to the payment service.
	RequestPaymentService *ecforce.BoolInt `json:"request_payment_service,omitempty"`
}

// CustomerMailRequest is the body of a SendMail request. Body is required for
// text mail; BodyHTML is required when UseHTML is true. CC and BCC each take
// at most one address.
type CustomerMailRequest struct {
	Subject  *string          `json:"subject,omitempty"`
	Body     *string          `json:"body,omitempty"`
	BodyHTML *string          `json:"body_html,omitempty"`
	CC       *string          `json:"cc,omitempty"`
	BCC      *string          `json:"bcc,omitempty"`
	UseHTML  *ecforce.BoolInt `json:"use_html,omitempty"`
}

// List searches customers.
//
// Supported q attributes: id, number, email, link_number,
// billing_address_s_full_tel, created_at, updated_at, with_deleted,
// member_groups_id, line_id_linked_at (lighter only).
// Supported sort attributes: id, created_at, updated_at.
// Supported include values: billing_address, shipping_addresses, notes,
// points, one_d_color_answers, one_d_color_answers.scores, orders,
// subs_orders, credit_cards, member_groups.
//
// ecforce API docs: GET /api/v2/admin/customers
func (s *CustomersService) List(ctx context.Context, opts *ecforce.ListOptions) ([]*ecforce.Resource[Customer], *ecforce.Response, error) {
	return ecforce.DoResourceList[Customer](ctx, s.client, http.MethodGet, "admin/customers.json", opts.Values(), nil)
}

// Get fetches a single customer.
//
// Supported include values: billing_address, shipping_addresses, notes,
// points, one_d_color_answers, one_d_color_answers.scores, orders,
// subs_orders, credit_cards, member_groups, customer_permitted_variants.
//
// ecforce API docs: GET /api/v2/admin/customers/:customer_id
func (s *CustomersService) Get(ctx context.Context, customerID int64, opts *ecforce.GetOptions) (*ecforce.Resource[Customer], *ecforce.Response, error) {
	path := fmt.Sprintf("admin/customers/%d.json", customerID)
	return ecforce.DoResource[Customer](ctx, s.client, http.MethodGet, path, opts.Values(), nil)
}

// Create registers a customer (synchronous).
//
// ecforce API docs: POST /api/v2/admin/customers
func (s *CustomersService) Create(ctx context.Context, req *CustomerCreateRequest) (*ecforce.Resource[Customer], *ecforce.Response, error) {
	return ecforce.DoResource[Customer](ctx, s.client, http.MethodPost, "admin/customers.json", nil, req)
}

// Update updates a customer (synchronous).
//
// ecforce API docs: PUT /api/v2/admin/customers/:customer_id
func (s *CustomersService) Update(ctx context.Context, customerID int64, req *CustomerUpdateRequest) (*ecforce.Resource[Customer], *ecforce.Response, error) {
	path := fmt.Sprintf("admin/customers/%d.json", customerID)
	return ecforce.DoResource[Customer](ctx, s.client, http.MethodPut, path, nil, req)
}

// BulkCreate registers customers in bulk (asynchronous); the returned
// JobResult identifies the accepted background job.
//
// ecforce API docs: POST /api/v2/admin/customers/bulk_create
func (s *CustomersService) BulkCreate(ctx context.Context, req *CustomerBulkRequest) (*ecforce.JobResult, *ecforce.Response, error) {
	result := new(ecforce.JobResult)
	resp, err := ecforce.Do(ctx, s.client, http.MethodPost, "admin/customers/bulk_create.json", nil, req, result)
	if err != nil {
		return nil, resp, err
	}
	return result, resp, nil
}

// BulkUpdate updates customers in bulk (synchronous). Each CustomerParams
// entry must set ID.
//
// ecforce API docs: PUT /api/v2/admin/customers/bulk_update
func (s *CustomersService) BulkUpdate(ctx context.Context, req *CustomerBulkRequest) (*ecforce.BulkResult, *ecforce.Response, error) {
	result := new(ecforce.BulkResult)
	resp, err := ecforce.Do(ctx, s.client, http.MethodPut, "admin/customers/bulk_update.json", nil, req, result)
	if err != nil {
		return nil, resp, err
	}
	return result, resp, nil
}

// BulkDestroy deletes customers in bulk (synchronous). Deleted customers
// cannot be restored.
//
// ecforce API docs: DELETE /api/v2/admin/customers/bulk_destroy
func (s *CustomersService) BulkDestroy(ctx context.Context, customerIDs []int64) (*ecforce.BulkResult, *ecforce.Response, error) {
	body := map[string]any{"customer_ids": customerIDs}
	result := new(ecforce.BulkResult)
	resp, err := ecforce.Do(ctx, s.client, http.MethodDelete, "admin/customers/bulk_destroy.json", nil, body, result)
	if err != nil {
		return nil, resp, err
	}
	return result, resp, nil
}

// CreatePoint creates a point ledger entry for the customer, updating the
// point total (synchronous).
//
// ecforce API docs: POST /api/v2/admin/customers/:customer_id/points
func (s *CustomersService) CreatePoint(ctx context.Context, customerID int64, params *PointParams) (*ecforce.Resource[Point], *ecforce.Response, error) {
	path := fmt.Sprintf("admin/customers/%d/points.json", customerID)
	return ecforce.DoResource[Point](ctx, s.client, http.MethodPost, path, nil, params)
}

// BulkCreatePoints creates point ledger entries for multiple customers,
// updating their point totals (synchronous).
//
// ecforce API docs: POST /api/v2/admin/customers/points/bulk_create
func (s *CustomersService) BulkCreatePoints(ctx context.Context, points []*CustomerPointParams) (*ecforce.BulkResult, *ecforce.Response, error) {
	body := map[string]any{"customer_points": points}
	result := new(ecforce.BulkResult)
	resp, err := ecforce.Do(ctx, s.client, http.MethodPost, "admin/customers/points/bulk_create.json", nil, body, result)
	if err != nil {
		return nil, resp, err
	}
	return result, resp, nil
}

// SendMail sends an email to the customer and returns the customer.
//
// ecforce API docs: POST /api/v2/admin/customers/:customer_id/emails
func (s *CustomersService) SendMail(ctx context.Context, customerID int64, req *CustomerMailRequest) (*ecforce.Resource[Customer], *ecforce.Response, error) {
	path := fmt.Sprintf("admin/customers/%d/emails.json", customerID)
	return ecforce.DoResource[Customer](ctx, s.client, http.MethodPost, path, nil, req)
}

// SendSMS sends an SMS with the given body to the customer and returns the
// customer. Bodies over 70 characters are sent as concatenated SMS and billed
// per segment.
//
// ecforce API docs: POST /api/v2/admin/customers/:customer_id/sms
func (s *CustomersService) SendSMS(ctx context.Context, customerID int64, body string) (*ecforce.Resource[Customer], *ecforce.Response, error) {
	path := fmt.Sprintf("admin/customers/%d/sms.json", customerID)
	reqBody := map[string]string{"body": body}
	return ecforce.DoResource[Customer](ctx, s.client, http.MethodPost, path, nil, reqBody)
}

// BulkCreateCreditCards registers credit cards for the customer in bulk
// (synchronous).
//
// ecforce API docs: POST /api/v2/admin/customers/:customer_id/credit_cards/bulk_create
func (s *CustomersService) BulkCreateCreditCards(ctx context.Context, customerID int64, req *CreditCardBulkRequest) (*ecforce.BulkResult, *ecforce.Response, error) {
	path := fmt.Sprintf("admin/customers/%d/credit_cards/bulk_create.json", customerID)
	result := new(ecforce.BulkResult)
	resp, err := ecforce.Do(ctx, s.client, http.MethodPost, path, nil, req, result)
	if err != nil {
		return nil, resp, err
	}
	return result, resp, nil
}

// BulkUpdateCreditCards updates the customer's credit cards in bulk
// (synchronous). Each CreditCardParams entry must set ID.
//
// ecforce API docs: PUT /api/v2/admin/customers/:customer_id/credit_cards/bulk_update
func (s *CustomersService) BulkUpdateCreditCards(ctx context.Context, customerID int64, req *CreditCardBulkRequest) (*ecforce.BulkResult, *ecforce.Response, error) {
	path := fmt.Sprintf("admin/customers/%d/credit_cards/bulk_update.json", customerID)
	result := new(ecforce.BulkResult)
	resp, err := ecforce.Do(ctx, s.client, http.MethodPut, path, nil, req, result)
	if err != nil {
		return nil, resp, err
	}
	return result, resp, nil
}

// BulkDestroyCreditCards deletes the customer's credit cards in bulk
// (synchronous).
//
// ecforce API docs: DELETE /api/v2/admin/customers/:customer_id/credit_cards/bulk_destroy
func (s *CustomersService) BulkDestroyCreditCards(ctx context.Context, customerID int64, req *CreditCardBulkDestroyRequest) (*ecforce.BulkResult, *ecforce.Response, error) {
	path := fmt.Sprintf("admin/customers/%d/credit_cards/bulk_destroy.json", customerID)
	result := new(ecforce.BulkResult)
	resp, err := ecforce.Do(ctx, s.client, http.MethodDelete, path, nil, req, result)
	if err != nil {
		return nil, resp, err
	}
	return result, resp, nil
}

// BulkDestroyShippingAddresses deletes the customer's shipping addresses in
// bulk (synchronous). Deleted addresses cannot be restored, and a customer
// cannot be left with zero shipping addresses.
//
// ecforce API docs: DELETE /api/v2/admin/customers/:customer_id/shipping_addresses/bulk_destroy
func (s *CustomersService) BulkDestroyShippingAddresses(ctx context.Context, customerID int64, shippingAddressIDs []int64) (*ecforce.BulkResult, *ecforce.Response, error) {
	path := fmt.Sprintf("admin/customers/%d/shipping_addresses/bulk_destroy.json", customerID)
	body := map[string]any{"shipping_address_ids": shippingAddressIDs}
	result := new(ecforce.BulkResult)
	resp, err := ecforce.Do(ctx, s.client, http.MethodDelete, path, nil, body, result)
	if err != nil {
		return nil, resp, err
	}
	return result, resp, nil
}

// ListFreeColumnValues fetches the customer's free column (custom field)
// values, grouped by category.
//
// ecforce API docs: GET /api/v2/admin/customers/:customer_id/free_column_values
func (s *CustomersService) ListFreeColumnValues(ctx context.Context, customerID int64) ([]*FreeColumnValueGroup, *ecforce.Response, error) {
	path := fmt.Sprintf("admin/customers/%d/free_column_values.json", customerID)
	var groups []*FreeColumnValueGroup
	resp, err := ecforce.Do(ctx, s.client, http.MethodGet, path, nil, nil, &groups)
	if err != nil {
		return nil, resp, err
	}
	return groups, resp, nil
}

// BulkCreateFreeColumnValues registers the customer's free column (custom
// field) values in bulk (synchronous).
//
// ecforce API docs: POST /api/v2/admin/customers/:customer_id/free_column_values/bulk_create
func (s *CustomersService) BulkCreateFreeColumnValues(ctx context.Context, customerID int64, freeColumns []*FreeColumnParams) (*ecforce.BulkResult, *ecforce.Response, error) {
	path := fmt.Sprintf("admin/customers/%d/free_column_values/bulk_create.json", customerID)
	body := map[string]any{"free_columns": freeColumns}
	result := new(ecforce.BulkResult)
	resp, err := ecforce.Do(ctx, s.client, http.MethodPost, path, nil, body, result)
	if err != nil {
		return nil, resp, err
	}
	return result, resp, nil
}

// BulkUpdateFreeColumnValues updates the customer's free column (custom
// field) values in bulk (synchronous).
//
// ecforce API docs: PUT /api/v2/admin/customers/:customer_id/free_column_values/bulk_update
func (s *CustomersService) BulkUpdateFreeColumnValues(ctx context.Context, customerID int64, freeColumns []*FreeColumnParams) (*ecforce.BulkResult, *ecforce.Response, error) {
	path := fmt.Sprintf("admin/customers/%d/free_column_values/bulk_update.json", customerID)
	body := map[string]any{"free_columns": freeColumns}
	result := new(ecforce.BulkResult)
	resp, err := ecforce.Do(ctx, s.client, http.MethodPut, path, nil, body, result)
	if err != nil {
		return nil, resp, err
	}
	return result, resp, nil
}

// ListBlacklistReasons searches blacklist reasons.
//
// Supported sort attributes: id, created_at, updated_at.
//
// ecforce API docs: GET /api/v2/admin/blacklist_reasons
func (s *CustomersService) ListBlacklistReasons(ctx context.Context, opts *ecforce.ListOptions) ([]*ecforce.Resource[BlacklistReason], *ecforce.Response, error) {
	return ecforce.DoResourceList[BlacklistReason](ctx, s.client, http.MethodGet, "admin/blacklist_reasons.json", opts.Values(), nil)
}
