package customer

import (
	"context"
	"net/http"

	"github.com/zero-color/ecforce-go"
)

// Customer is the authenticated customer's own record. It is the attribute
// union of the normal and lighter response variants: the *ID fields
// (CustomerRankID, JobID, CustomerTypeID, LineIDLinkedAt) come from the
// lighter variant, while the resolved names (CustomerRankName, Sex, Job,
// CustomerTypeName) and the point/blacklist attributes come from the normal
// variant.
type Customer struct {
	ID                    int64         `json:"id"`
	AuthenticationToken   string        `json:"authentication_token"`
	Number                string        `json:"number"`
	State                 string        `json:"state"`
	HumanStateName        string        `json:"human_state_name"`
	CustomerRankID        int64         `json:"customer_rank_id"`
	CustomerRankName      string        `json:"customer_rank_name"`
	Email                 string        `json:"email"`
	MobileEmail           string        `json:"mobile_email"`
	SexID                 int64         `json:"sex_id"`
	Sex                   string        `json:"sex"`
	JobID                 int64         `json:"job_id"`
	Job                   string        `json:"job"`
	Birth                 string        `json:"birth"`
	BuyTimes              int           `json:"buy_times"`
	BuyTotal              int           `json:"buy_total"`
	FirstOrderCompletedAt *ecforce.Time `json:"first_order_completed_at"`
	LastOrderCompletedAt  *ecforce.Time `json:"last_order_completed_at"`
	Point                 int           `json:"point"`
	PointExpiredAt        *ecforce.Time `json:"point_expired_at"`
	CustomerTypeID        int64         `json:"customer_type_id"`
	CustomerTypeName      string        `json:"customer_type_name"`
	Optin                 bool          `json:"optin"`
	LineID                string        `json:"line_id"`
	LineIDLinkedAt        *ecforce.Time `json:"line_id_linked_at"`
	TenantID              int64         `json:"tenant_id"`
	AssignedAdminID       int64         `json:"assigned_admin_id"`
	LinkedMemo            string        `json:"linked_memo"`
	MailDeliveryStop      bool          `json:"mail_delivery_stop"`
	NPRoyalCustomer       bool          `json:"np_royal_customer"`
	Blacklist             bool          `json:"blacklist"`
	BlacklistReasons      string        `json:"blacklist_reasons"`
	Labels                string        `json:"labels"`
	CouponCodes           string        `json:"coupon_codes"`
	LinkNumber            string        `json:"link_number"`
	IsAutoGeneratedEmail  bool          `json:"is_auto_generated_email"`
	AuthInfrastructureID  string        `json:"auth_infrastructure_id"`
	Option01              string        `json:"option01"`
	Option02              string        `json:"option02"`
	Option03              string        `json:"option03"`
	Option04              string        `json:"option04"`
	Option05              string        `json:"option05"`
	Option06              string        `json:"option06"`
	Option07              string        `json:"option07"`
	Option08              string        `json:"option08"`
	Option09              string        `json:"option09"`
	Option10              string        `json:"option10"`
	CreatedAt             *ecforce.Time `json:"created_at"`
	UpdatedAt             *ecforce.Time `json:"updated_at"`
	DeletedAt             *ecforce.Time `json:"deleted_at"`
}

// CustomerParams are the attributes of CustomerService.Update.
type CustomerParams struct {
	Email                       *string          `json:"email,omitempty"`
	Optin                       *ecforce.BoolInt `json:"optin,omitempty"`
	Password                    *string          `json:"password,omitempty"`
	CustomerTypeID              *int64           `json:"customer_type_id,omitempty"`
	LineID                      *string          `json:"line_id,omitempty"`
	TenantID                    *int64           `json:"tenant_id,omitempty"`
	LinkNumber                  *string          `json:"link_number,omitempty"`
	BillingAddressAttributes    *AddressParams   `json:"billing_address_attributes,omitempty"`
	ShippingAddressesAttributes []*AddressParams `json:"shipping_addresses_attributes,omitempty"`
	NotesAttributes             []*NoteParams    `json:"notes_attributes,omitempty"`
}

// Get fetches the authenticated customer's own record.
//
// Supported include values: billing_address, shipping_addresses, notes,
// orders, orders.billing_address, orders.shipping_address, subs_orders.
//
// ecforce API docs: GET /api/v2/customer
func (s *CustomerService) Get(ctx context.Context, opts *ecforce.GetOptions) (*ecforce.Resource[Customer], *ecforce.Response, error) {
	return ecforce.DoResource[Customer](ctx, s.client, http.MethodGet, "customer.json", opts.Values(), nil)
}

// Update updates the authenticated customer's own record (synchronous).
//
// ecforce API docs: PUT /api/v2/customer
func (s *CustomerService) Update(ctx context.Context, params *CustomerParams) (*ecforce.Resource[Customer], *ecforce.Response, error) {
	body := map[string]any{"customer": params}
	return ecforce.DoResource[Customer](ctx, s.client, http.MethodPut, "customer.json", nil, body)
}
